/**
 * DEX allowlist for GeckoTerminal API support
 * Auto-generated from GT API data on 2025-08-17T18:36:01.748Z
 * 
 * Total networks: 100
 * Total unique DEXes: 1127
 */

// All supported DEXes across all networks
export const ALLOW = new Set([
  '10kswap-starknet-alpha',
  '1bch',
  '3xcalibur',
  '9inch',
  '9inch-ethereum',
  '9mm-v2',
  '9mm-v2-base',
  '9mm-v3',
  '9mm-v3-base',
  'acsi-finance',
  'aegis',
  'aerodrome-base',
  'aerodrome-slipstream',
  'agni-finance',
  'agora_swap',
  'ags_finance',
  'agus-dex-core',
  'algebra_finance',
  'alien-base',
  'alien-base-v3',
  'aliendex',
  'alienfi',
  'alium',
  'allinxswap-bsc',
  'allinxswap-opbnb',
  'amaterasu',
  'ampleswap-bsc',
  'animeswap',
  'annex_finance',
  'annex_finance_bsc',
  'antfarm-arbitrum',
  'antfarm-avalanche',
  'antfarm-ethereum',
  'antfarm-polygon-zkevm',
  'apertureswap',
  'apeswap-arbitrum',
  'apeswap_bsc',
  'apeswap_ethereum',
  'apeswap_polygon',
  'apeswap_telos',
  'apexswap',
  'aquaspace',
  'arbidex',
  'arbidex-v3',
  'arbiswap',
  'arbswap-stableswap-arbitrum',
  'arbswap-stableswap-arbitrum-nova',
  'arbswap_arbitrum_nova',
  'arbswap_arbitrum_one',
  'archerswap',
  'archly-arbitrum',
  'archly-arbitrum-nova',
  'archly-avalanche',
  'archly-base',
  'archly-bsc',
  'archly-cronos',
  'archly-ethereum',
  'archly-filecoin',
  'archly-ftm',
  'archly-kava',
  'archly-mantle',
  'archly-metis',
  'archly-mode',
  'archly-neon',
  'archly-optimism',
  'archly-polygon',
  'archly-telos',
  'archly-zksync',
  'area-51-alien-base',
  'arena-dex',
  'arthswap',
  'astar-exchange-v3',
  'astar_exchange',
  'astroport-sei',
  'astroswap',
  'auragi',
  'auraswap',
  'auroraswap',
  'autoshark_finance',
  'aux',
  'babydogeswap',
  'babyswap',
  'baguette',
  'bakeryswap',
  'bakeryswap-base',
  'balancer-gnosis',
  'balancer-v2-avalanche',
  'balancer-v2-base',
  'balancer-v2-mode',
  'balancer-v2-polygon-zkevm',
  'balancer-v3-arbitrum',
  'balancer-v3-avalanche',
  'balancer-v3-base',
  'balancer-v3-ethereum',
  'balancer-v3-gnosis',
  'balancer-v3-optimism',
  'balancer_arbitrum',
  'balancer_ethereum',
  'balancer_polygon',
  'ball-exchange-shibarium',
  'bao_finance',
  'baptswap',
  'baryon-network-bitkub-chain',
  'baryon-network-viction',
  'baryon_network',
  'baseswap',
  'baseswap-v3',
  'basex',
  'baso-finance',
  'beam-swap',
  'beamswap',
  'beamswap-v3',
  'becoswap',
  'beethoven_x_fantom',
  'beethoven_x_optimism',
  'benswap',
  'binaryswap',
  'biswap',
  'biswap-v3',
  'biswap-v3-1',
  'bitswap',
  'blackhole-v2',
  'blackhole-v3',
  'blazeswap',
  'blazeswap-flare',
  'bluedex',
  'bluefin',
  'bluemove',
  'blueprint',
  'boop-fun',
  'bossswap',
  'bourbon_defi',
  'bridges',
  'bunni-arbitrum',
  'bunni-base',
  'bunni-ethereum',
  'bunnyswap',
  'butter-xyz',
  'byreal',
  'cakewswap',
  'cakewswap_bsc',
  'camelot',
  'camelot-v3',
  'canary-exchange',
  'candycity_finance',
  'candyswap',
  'canto_dex',
  'cantoswap',
  'capybaradex-v2',
  'capybaradex-v3',
  'cattieswap',
  'cbswap',
  'celodex',
  'cetoswap',
  'cetus',
  'chewyswap',
  'chimp-exchange',
  'chronos',
  'citadelswap',
  'claimswap',
  'cleopatra-exchange',
  'cloudbase',
  'cmswap-kub',
  'coffee-dex',
  'comethswap',
  'concave',
  'cone_exchange',
  'convergence-finance-v2',
  'corex',
  'corgiswap',
  'cougar_exchange',
  'cowswap_smartbch',
  'creamswap',
  'crescentswap',
  'crescentswap-base',
  'crodex',
  'cronaswap',
  'cronus_finance',
  'croswap',
  'crowdswap-polygon',
  'crowfi',
  'crust-finance',
  'crust-finance-v2',
  'cuanswap',
  'cubiswap',
  'curve',
  'curve-base',
  'curve-celo',
  'curve-gnosis',
  'curve-kava',
  'curve-xdc',
  'curve_arbitrum',
  'curve_avalanche',
  'curve_ftm',
  'curve_moonbeam',
  'curve_optimism',
  'curve_polygon_pos',
  'cyberglow',
  'cyborgswap',
  'dackieswap-v2-arbitrum',
  'dackieswap-v2-base',
  'dackieswap-v2-linea',
  'dackieswap-v2-mode',
  'dackieswap-v2-optimism',
  'dackieswap-v3-arbitrum',
  'dackieswap-v3-base',
  'dackieswap-v3-linea',
  'dackieswap-v3-mode',
  'dackieswap-v3-optimism',
  'dao_swap',
  'daos-fun',
  'darkknight',
  'darwinswap',
  'dddx',
  'dedust',
  'defi_kingdoms',
  'defi_kingdoms_crystalvale',
  'defi_kingdoms_serendale',
  'defi_swap',
  'definix',
  'degen-express',
  'degenbrains',
  'degenbrains-base',
  'degendex-bsc',
  'degendex-dogechain',
  'degenswap',
  'dejungle',
  'deltaswap',
  'deltaswap-base',
  'deltaswap-ethereum',
  'derpdex',
  'derpdex-base',
  'derpdex-opbnb',
  'dex-on-crypto',
  'dex-on-crypto-arbitrum',
  'dex-on-crypto-avalanche',
  'dex-on-crypto-base',
  'dex-on-crypto-core',
  'dex-on-crypto-ethereum',
  'dex-on-crypto-opbnb',
  'dex-on-crypto-polygon',
  'dex-on-crypto-shibarium',
  'dexlab',
  'dexswap',
  'dextop',
  'dfyn',
  'dfyn_fantom',
  'diamon_finance',
  'diamondswap',
  'diamondswap-bsc',
  'diffusion',
  'dinosaureggs',
  'dinoswap',
  'dipoleswap',
  'dogeshrek',
  'dogeswap',
  'dogswap',
  'donaswap-v3-bsc',
  'dooar-polygon',
  'dooar_bsc',
  'dooar_ethereum',
  'doveswap-v3',
  'dracula-finance',
  'dragonswap-v2-kaia',
  'dragonswap-v3',
  'duckydefi',
  'duneswap',
  'dyorswap-mode',
  'dystopia',
  'eazyswap',
  'ebisus-bay',
  'echodex',
  'ekubo',
  'ekubo-ethereum',
  'elektrik',
  'elk-finance-neon',
  'elk_finance',
  'elk_finance_arbitrum',
  'elk_finance_avax',
  'elk_finance_bittorrent',
  'elk_finance_bsc',
  'elk_finance_elastos',
  'elk_finance_ethereum',
  'elk_finance_ftm',
  'elk_finance_fuse',
  'elk_finance_iotex',
  'elk_finance_kava',
  'elk_finance_kcc',
  'elk_finance_movr',
  'elk_finance_one',
  'elk_finance_optimism',
  'elk_finance_polygon',
  'elk_finance_telos',
  'elk_finance_xdai',
  'ellipsis_finance',
  'elves-dex',
  'elysiumswap',
  'emberswap',
  'emojicoin-fun',
  'empiredex_bsc',
  'empiredex_cronos',
  'energiswap',
  'enosys-dex',
  'enosys-dex-v3',
  'enosys-flare',
  'enosys-v3-flare',
  'ensurer',
  'eoswap-finance',
  'equalizer',
  'equalizer-base',
  'equilibre',
  'etcmc',
  'etcswap-v2',
  'etcswap-v3',
  'etherex',
  'ethervista',
  'ethervista-arbitrum',
  'ethervista-base',
  'evmoswap',
  'excalibur',
  'ezkalibur',
  'fairyswap',
  'falcox-swap',
  'fathom-dex',
  'fbomb_finance',
  'featherswap',
  'firebird_avax',
  'firebird_bsc',
  'firebird_cronos',
  'firebird_fantom',
  'firebird_finance_polygon',
  'firebird_movr',
  'firefly',
  'flair-dex',
  'flameswap',
  'flow-x',
  'flowx-clmm',
  'fluxbeam',
  'forge',
  'forge-sx',
  'forteswap',
  'fourdex',
  'foxswap',
  'fraxswap_arbitrum',
  'fraxswap_avalanche',
  'fraxswap_bsc',
  'fraxswap_dogechain',
  'fraxswap_ethereum',
  'fraxswap_fantom',
  'fraxswap_moonbeam',
  'fraxswap_moonriver',
  'fraxswap_optimism',
  'fraxswap_polygon_pos',
  'frogge-finance',
  'fstswap',
  'fullsail-finance',
  'funbeast',
  'function-island',
  'funny-money',
  'furyswap-zkfair',
  'fusionx-v2',
  'fusionx-v3',
  'fuzz_finance',
  'fwx',
  'fwx-base',
  'gaming-dex-oasys',
  'gasx',
  'gemkeeper',
  'gemswap',
  'glacier',
  'glide_finance',
  'globiance',
  'glyph-exchange-v2',
  'glyph-exchange-v4',
  'gravity_finance',
  'greenhouse_dex',
  'gt3',
  'gull-network',
  'hakuswap',
  'hebeswap',
  'heliswap',
  'henjin',
  'hercules-v2',
  'hercules-v3',
  'hermes_protocol',
  'hermesdefi',
  'hexaswap',
  'hkswap',
  'holdr',
  'holdstation',
  'honeyswap',
  'honeyswap_polygon',
  'hopeswap',
  'horizondex',
  'horizondex-base',
  'huckleberry',
  'hunnyswap',
  'hurricaneswap',
  'hydrex-integral',
  'hyperion',
  'hyperjump_ftm',
  'hyperjump_metis',
  'icecreamswap',
  'icecreamswap-base',
  'icecreamswap-core',
  'icecreamswap-neon',
  'icecreamswap-scroll',
  'icecreamswap-shimmerevm',
  'icecreamswap-telos',
  'icecreamswap-v3-core',
  'icecreamswap-xdc',
  'impossible-finance-humanode',
  'impossible_finance',
  'impossible_finance_v3',
  'infusion',
  'integral_size',
  'intercroneswap-bittorent',
  'intercroneswap-bsc',
  'iotabee-shimmerevm',
  'ix-swap',
  'iziswap-base',
  'iziswap-bsc',
  'iziswap-kava',
  'iziswap-linea',
  'iziswap-manta-pacific',
  'iziswap-mantle',
  'iziswap-mode',
  'iziswap-scroll',
  'iziswap-v2-zksync',
  'iziswap-zkfair',
  'iziswap-zksync',
  'jediswap-starknet-alpha',
  'jetswap_bsc',
  'jetswap_fantom',
  'jetswap_polygon',
  'jswap_bsc',
  'julswap',
  'jupiter_swap',
  'justmoney-ethereum',
  'justmoney_bsc',
  'justmoney_bttc',
  'justmoney_polygon_pos',
  'kaiaswap-klaytn',
  'kaidex',
  'kaidex_v3',
  'kaleidoswap-arbitrum',
  'katana',
  'katana-v3',
  'kewlswap-arbitrum',
  'kewlswap-base',
  'khaos_exchange',
  'kibbleswap',
  'kim',
  'kim-v2-base',
  'kim-v4',
  'kim-v4-base',
  'kinetix-v3',
  'klayswap',
  'klayswap-v3',
  'knightdex',
  'knightswap',
  'koi-finance-v3',
  'kokonutswap-base',
  'kriya-dex',
  'kryptodex',
  'kuswap',
  'kyberswap-elastic-base',
  'kyberswap-elastic-linea',
  'kyberswap-elastic-scroll',
  'kyberswap_classic_arbitrum',
  'kyberswap_classic_avalanche',
  'kyberswap_classic_bsc',
  'kyberswap_classic_bttc',
  'kyberswap_classic_ethereum',
  'kyberswap_classic_fantom',
  'kyberswap_classic_optimism',
  'kyberswap_classic_polygon',
  'kyberswap_elastic',
  'kyberswap_elastic_arbitrum',
  'kyberswap_elastic_avalanche',
  'kyberswap_elastic_bsc',
  'kyberswap_elastic_cronos',
  'kyberswap_elastic_fantom',
  'kyberswap_elastic_optimism',
  'kyberswap_elastic_polygon',
  'kyotoswap',
  'laserswap',
  'lawswap',
  'leetswap-base',
  'leetswap-canto',
  'leetswap-linea',
  'leetswap-manta',
  'leetswap-polygon-zkevm',
  'leetswap-scroll',
  'leetswap-shibarium',
  'leetswap-zkevm',
  'leonicornswap',
  'levinswap_xdai',
  'lfgswap',
  'lfgswap-arbitrum',
  'lfgswap-base',
  'lfgswap-core',
  'lif3',
  'lif3-bsc',
  'lif3-ethereum',
  'lif3-polygon',
  'lif3-v3-bsc',
  'lif3-v3-fantom',
  'lif3-v3-polygon',
  'line-hub-v2',
  'line-hub-v3',
  'liquidswap',
  'liquidswap-v0-5',
  'lizard-exchange',
  'lootswap',
  'lovely-swap',
  'loxodrome-iotex',
  'luigiswap',
  'luigiswap-scroll',
  'lunardex',
  'lydia_finance',
  'lynex-linea',
  'lynex-v2-linea',
  'magicfox',
  'magicswap',
  'magikswap',
  'magma-finance',
  'mama-defi',
  'mantaswap',
  'mars_ecosystem',
  'marswap',
  'marswap-base',
  'marswap-ethereum',
  'maverick-v2-arbitrum',
  'maverick-v2-base',
  'maverick-v2-eth',
  'maverick-v2-scroll',
  'maverick-v2-zksync',
  'mdex-bittorent',
  'mdex_bsc',
  'melegaswap',
  'memebox-base',
  'memebox-fantom',
  'merchant-moe-liquidity-book-mantle',
  'merchant-moe-mantle',
  'meridian-swap',
  'merlin-dex',
  'mermaidswap',
  'meshswap',
  'metavault-v2-linea',
  'metavault-v2-scroll',
  'metavault-v3-linea',
  'metavault-v3-scroll',
  'meteora',
  'meteora-damm-v2',
  'meteora-dbc',
  'methlab',
  'metropolis',
  'miaswap',
  'milkyswap-milkada',
  'mimo',
  'mindgames',
  'mindgames-arbitrum',
  'mistswap',
  'mm-finance-arbitrum',
  'mm-finance-polygon',
  'mm-finance-v3-arbitrum',
  'mm-finance-v3-cronos',
  'mm_finance',
  'mobydEX',
  'mojitoswap',
  'momentum',
  'moonbase',
  'moonbase-alpha',
  'moonlift',
  'moraswap-v2',
  'moraswap-v3',
  'morpheus_swap',
  'movepump-aptos',
  'muesliswap-milkada',
  'mute',
  'mxc-swap',
  'nachoswap',
  'nearpad',
  'netswap',
  'neutroswap',
  'nexus',
  'nile',
  'nile-v1',
  'niob',
  'noahswap',
  'nomiswap',
  'nomiswap_stable',
  'nostra',
  'nskswap',
  'nuri-legacy',
  'nuri-v2',
  'oasisswap',
  'oasisswap-base',
  'occamx',
  'oku-trade-boba',
  'oku-trade-filecoin',
  'oku-trade-gnosis',
  'oku-trade-linea',
  'oku-trade-manta-pacific',
  'oku-trade-moonbeam',
  'oku-trade-polygon-zkevm',
  'oku-trade-scroll',
  'oku-trade-telos',
  'oku-trade-xdc',
  'omni-exchange-v2-arbitrum',
  'omni-exchange-v2-avalanche',
  'omni-exchange-v2-base',
  'omni-exchange-v2-optimism',
  'omni-exchange-v3-arbitrum',
  'omni-exchange-v3-avalanche',
  'omni-exchange-v3-base',
  'omni-exchange-v3-optimism',
  'omni-exchange-v4-avalanche',
  'omni-exchange-v4-base',
  'omnidex',
  'onavax',
  'onsen-swap',
  'oolongswap',
  'opbnbswap',
  'openex-core',
  'openocean',
  'openswap',
  'openxswap',
  'oracleswap',
  'orbitalswap',
  'orca',
  'oreoswap',
  'oreswap-core',
  'orion-bsc',
  'orion-ethereum',
  'orion-fantom',
  'orion-polygon',
  'pacificswap',
  'padswap-bsc',
  'padswap_moonbeam',
  'paintswap',
  'pancakeswap-infinity-clmm-base',
  'pancakeswap-stableswap-arbitrum',
  'pancakeswap-stableswap-ethereum',
  'pancakeswap-v1-bsc',
  'pancakeswap-v2-arbitrum',
  'pancakeswap-v2-base',
  'pancakeswap-v2-linea',
  'pancakeswap-v2-opbnb',
  'pancakeswap-v2-polygon-zkevm',
  'pancakeswap-v2-zksync',
  'pancakeswap-v3-arbitrum',
  'pancakeswap-v3-base',
  'pancakeswap-v3-bsc',
  'pancakeswap-v3-ethereum',
  'pancakeswap-v3-linea',
  'pancakeswap-v3-opbnb',
  'pancakeswap-v3-polygon-zkevm',
  'pancakeswap-v3-solana',
  'pancakeswap-v3-zksync',
  'pancakeswap_aptos',
  'pancakeswap_ethereum',
  'pancakeswap_stableswap',
  'pancakeswap_v2',
  'pandora_digital_swap',
  'pangolin',
  'pangolin-flare',
  'pangolin-songbird',
  'pangolin-v3',
  'papyrus-swap',
  'pdex-vision',
  'pearl-exchange',
  'pearlfi-v1-5',
  'pegasys-v3-rollux',
  'pepedex',
  'pharaoh-exchange',
  'pharaoh-exchange-v1',
  'pheasantswap',
  'pheasantswap-linea',
  'phenix-finance-cronos',
  'phenix-finance-polygon',
  'photonswap',
  'photonswap_kava',
  'phux',
  'pinkswap',
  'pipiswap',
  'piswap',
  'pixelswap-arbitrum',
  'pixelswap-base',
  'pixelswap-linea',
  'pixelswap-opbnb',
  'pixelswap-zksync',
  'planet_finance',
  'plantbaseswap',
  'pls2e',
  'polaris',
  'polaris-telos',
  'polkaex_astar',
  'polkaex_bsc',
  'polkaex_shiden',
  'polycat_finance',
  'polydex',
  'ponder-finance',
  'poolshark',
  'popswap',
  'powerswap',
  'powswap',
  'protofi',
  'pulse-rate',
  'pulsegun',
  'pulsex',
  'pulsex-v2',
  'pump-fun',
  'pumpswap',
  'punkswap',
  'punkswap-shibarium',
  'puppyswap',
  'pupswap',
  'purplebridge',
  'pyeswap_bsc',
  'pyreswap-avalanche',
  'pyreswap-fantom',
  'quickswap',
  'quickswap-polygon-zkevm',
  'quickswap-v2-base',
  'quickswap-v3-manta-pacific',
  'quickswap-v4-base',
  'quickswap_dogechain',
  'quickswap_v3',
  'quillswap',
  'rabbitswap',
  'radioshack-dogechain',
  'radioshack-ethw',
  'radioshack_avalanche',
  'radioshack_bsc',
  'radioshack_cronos',
  'radioshack_ethereum',
  'radioshack_fantom',
  'radioshack_optimism',
  'radioshack_polygon_pos',
  'ramses',
  'ramses-v2',
  'raydium',
  'raydium-clmm',
  'raydium-launchlab',
  'rcpswap',
  'redemption',
  'retherswap',
  'retro',
  'rexdex',
  'ring-exchange-ethereum',
  'robots-farm-base',
  'rocketswap',
  'rocketswap-opbnb',
  'rockswap',
  'rubicon-base',
  'rubicon-optimism',
  'safemoon_swap',
  'safemoonswap-polygon',
  'safemoonswap_ethereum',
  'saitaswap-bsc',
  'saitaswap-ethereum',
  'sakeswap',
  'sanctuary',
  'saros-amm',
  'saros-dlmm',
  'sashimiswap',
  'satin-exchange',
  'satori-base',
  'satori-linea',
  'satoshicoreswap',
  'saucerswap',
  'saucerswap-v2',
  'scribe',
  'scrollswap',
  'seadex',
  'secta-finance-v2',
  'secta-finance-v3',
  'shadowswap',
  'sharkswap',
  'sharkswap-base',
  'sharkyswap',
  'shekelswap',
  'shibarium-fun',
  'shibaswap',
  'shibaswap-shibarium',
  'shibbex',
  'shimmersea',
  'shiniswap',
  'shipedex',
  'sideswap',
  'skeleton-finance',
  'skullswap',
  'skydrome',
  'skydrome-v2',
  'smardex-arbitrum',
  'smardex-base',
  'smardex-bsc',
  'smardex-ethereum',
  'smardex-polygon',
  'sobal',
  'sobal-base',
  'solarbeam',
  'solarflare',
  'solidlizard',
  'solidly',
  'solidly-v3',
  'solidly-v3-arbitrum',
  'solidly-v3-base',
  'solidly-v3-fantom',
  'solidly-v3-optimism',
  'solidlydex',
  'solisnek',
  'solunea',
  'solunea-arbitrum',
  'soswap',
  'soulswap',
  'soulswap_avalanche',
  'soy_finance_etc',
  'spacefi',
  'spacefi-scroll',
  'spacefi_zksync',
  'sparkdex-v2',
  'sparkdex-v3',
  'sparkdex-v3-1',
  'sparkswap',
  'spartadex',
  'sphynx-loop-network',
  'sphynx_brise',
  'sphynx_swap',
  'spice_trade_avalanche',
  'spice_trade_bsc',
  'spice_trade_ethereum',
  'spice_trade_polygon',
  'spinaqdex',
  'spiritswap',
  'spiritswap_v2',
  'spookyswap',
  'spookyswap-bittorent',
  'spookyswap-v3',
  'spoon-exchange',
  'squadswap-base',
  'squadswap-v2-arbitrum',
  'squadswap-v2-optimism',
  'squadswap-v2-polygon',
  'squadswap-v3-arbitrum',
  'squadswap-v3-base',
  'squadswap-v3-optimism',
  'squadswap-v3-polygon',
  'standard',
  'standard_ethereum',
  'standard_protocol',
  'starkdefi',
  'starmaker',
  'starswap',
  'stellaswap',
  'stellaswap-v3',
  'stellaswap-v4',
  'step-exchange',
  'sterling',
  'stonfi',
  'stonfi-v2',
  'stratum-exchange',
  'stronghands-dex-v2',
  'suiswap',
  'superswap',
  'supswap',
  'surfswap',
  'surge-protocol-bsc',
  'surge-protocol-eth',
  'sushiswap',
  'sushiswap-aptos',
  'sushiswap-boba',
  'sushiswap-v2-base',
  'sushiswap-v2-bittorrent',
  'sushiswap-v2-core',
  'sushiswap-v2-filecoin',
  'sushiswap-v2-kava',
  'sushiswap-v2-linea',
  'sushiswap-v2-metis',
  'sushiswap-v2-optimism',
  'sushiswap-v2-polygon-zkevm',
  'sushiswap-v2-scroll',
  'sushiswap-v2-thundercore',
  'sushiswap-v3-arbitrum',
  'sushiswap-v3-arbitrum-nova',
  'sushiswap-v3-avalanche',
  'sushiswap-v3-base',
  'sushiswap-v3-bittorrent',
  'sushiswap-v3-boba',
  'sushiswap-v3-bsc',
  'sushiswap-v3-core',
  'sushiswap-v3-ethereum',
  'sushiswap-v3-fantom',
  'sushiswap-v3-filecoin',
  'sushiswap-v3-fuse',
  'sushiswap-v3-gnosis',
  'sushiswap-v3-kava',
  'sushiswap-v3-linea',
  'sushiswap-v3-metis',
  'sushiswap-v3-moonbeam',
  'sushiswap-v3-moonriver',
  'sushiswap-v3-optimism',
  'sushiswap-v3-polygon',
  'sushiswap-v3-polygon-zkevm',
  'sushiswap-v3-scroll',
  'sushiswap-v3-thundercore',
  'sushiswap_arbitrum',
  'sushiswap_arbitrum_nova',
  'sushiswap_avalanche',
  'sushiswap_bsc',
  'sushiswap_celo',
  'sushiswap_fantom',
  'sushiswap_fuse',
  'sushiswap_harmony',
  'sushiswap_moonriver',
  'sushiswap_polygon_pos',
  'sushiswap_telos',
  'sushiswap_xdai',
  'swap-country',
  'swapbased',
  'swapbased-v3',
  'swapfish',
  'swapline-base',
  'swapline-optimism',
  'swapline-shimmerevm',
  'swapmode',
  'swapperchan',
  'swappi',
  'swapr_arbitrum',
  'swapr_ethereum',
  'swapr_xdai',
  'swaprum',
  'swapsicle',
  'swapsicle-telos',
  'swapsicle-v2-mantle',
  'swapsicle-v2-telos',
  'swych',
  'symmetric-finance',
  'symmetric-finance-meter',
  'syncswap',
  'syncswap-linea',
  'syncswap-scroll',
  'syncswap-v2-1-linea',
  'syncswap-v2-1-scroll',
  'syncswap-v2-1-zksync',
  'syncswap-v2-zksync',
  'syncswap-v3-zksync',
  'synthswap',
  'synthswap-v3',
  'tangleswap-milkomeda-cardano',
  'tangleswap-shimmerevm',
  'tangoswap',
  'tealswap',
  'tealswap-v3',
  'templedao',
  'tendieswap',
  'tenx',
  'tethys',
  'tetuswap',
  'themis-pro',
  'thena',
  'thena-fusion',
  'thena-opbnb',
  'thorus',
  'thorus_moonbeam',
  'throne-v2-base',
  'throne-v3-base',
  'tokan-exchange',
  'tomb_swap_fantom',
  'toolswap',
  'torrswap',
  'torus',
  'traderjoe',
  'traderjoe-bsc',
  'traderjoe-v2-1-arbitrum',
  'traderjoe-v2-1-avalanche',
  'traderjoe-v2-1-bsc',
  'traderjoe-v2-1-ethereum',
  'traderjoe-v2-2-arbitrum',
  'traderjoe-v2-2-avalanche',
  'traderjoe-v2-arbitrum',
  'traderjoe-v2-avalanche',
  'traderjoe-v2-bsc',
  'tranquil_finance',
  'treble-v2',
  'treble-v4',
  'trisolaris',
  'tropical_finance',
  'tropicalswap',
  'turbos-finance',
  'ubeswap',
  'ubeswap-v3',
  'udex',
  'udonswap',
  'ultronswap',
  'unicly',
  'uniswap-bsc',
  'uniswap-v2-arbitrum',
  'uniswap-v2-avalanche',
  'uniswap-v2-base',
  'uniswap-v2-bsc',
  'uniswap-v2-optimism',
  'uniswap-v2-polygon',
  'uniswap-v2-sepolia-testnet',
  'uniswap-v3-avalanche',
  'uniswap-v3-base',
  'uniswap-v3-sepolia-testnet',
  'uniswap-v3-zksync',
  'uniswap-v4-arbitrum',
  'uniswap-v4-avalanche',
  'uniswap-v4-base',
  'uniswap-v4-ethereum',
  'uniswap-v4-optimism',
  'uniswap-v4-polygon',
  'uniswap_v2',
  'uniswap_v2_ethpow',
  'uniswap_v3',
  'uniswap_v3_arbitrum',
  'uniswap_v3_celo',
  'uniswap_v3_optimism',
  'uniswap_v3_polygon_pos',
  'uniwswap',
  'usdfi',
  'valleyswap',
  'vanillaswap-v2-defimetachain',
  'vanillaswap-v3-defimetachain',
  'vapordex',
  'vapordex-v2',
  'vapordex-v2-telos',
  'vax',
  'velocimeter',
  'velocimeter-base',
  'velocimeter-fantom',
  'velocimeter-mantle',
  'velocimeter-pulsechain',
  'velocimeter-v3',
  'velocimeter_v2',
  'velocore',
  'velocore-v2-linea',
  'velocore-v2-telos',
  'velocore-v2-zksync',
  'velodrome',
  'velodrome-finance-slipstream',
  'velodrome-finance-slipstream-celo',
  'velodrome-finance-slipstream-mode',
  'velodrome-finance-v2',
  'velodrome-finance-v2-mode',
  'veplus',
  'versa',
  'verse',
  'vesync',
  'vibrant-finance',
  'viperswap',
  'viridian',
  'virtuals-base',
  'virtuals-solana',
  'voltage-finance-v3',
  'voltage-finance-v4',
  'voltage_finance',
  'voltswap_meter',
  'vulcandex',
  'vvs',
  'vvs-v3',
  'vvs-v3-ethereum',
  'w-dex-polygon',
  'w3swap',
  'wagmi-ethereum',
  'wagmi-fantom',
  'wagmi-kava',
  'wagmi-metis',
  'wagmi-zksync',
  'wagmidao',
  'wagyuswap',
  'wannaswap',
  'wanswap',
  'wault_finance',
  'wault_finance_polygon',
  'wavelength',
  'wemix_fi',
  'whaleswap',
  'whitehole-arbitrum',
  'whiteswap',
  'wigoswap',
  'winery_swap',
  'wingswap',
  'wizardswap-core',
  'wizardswap-pulsechain',
  'wojak-finance-dogechain',
  'woken-exchange-arbitrum',
  'woken-exchange-bsc',
  'woof-finance',
  'woofswap',
  'woofswap-core',
  'x7-finance',
  'x7-finance-base',
  'x7-finance-ethereum',
  'xenos-swap-flare',
  'xenos-swap-songbird',
  'xflows',
  'xswap',
  'xswap-v3',
  'yetiswap',
  'yodeswap',
  'yokaiswap',
  'yoshi_exchange_bsc',
  'yoshi_exchange_ftm',
  'yum-yum-swap',
  'yuzuswap_oasis_emerald',
  'z-protocol',
  'zadafinance',
  'zappy',
  'zebra-scroll',
  'zebra-v2-scroll',
  'zenlink_astar',
  'zenlink_moonbeam',
  'zenlink_moonriver',
  'zergswap-v2',
  'zergswap-v3',
  'zipswap',
  'zircon',
  'zkfairswap-zkfair',
  'zkswap-finance',
  'zkswap-finance-stableswap',
  'zkswap-v3',
  'zyberswap',
]);

// Priority DEXes (commonly used across multiple networks)
export const PRIORITY_DEXES = new Set([
  'uniswap_v2',
  'uniswap_v3', 
  'sushiswap',
  'pancakeswap_v2',
  'pancakeswap_v3',
  'quickswap',
  'trader_joe_v2',
  'spookyswap',
  'spiritswap',
  'curve',
  'balancer_v2',
  'orca',
  'raydium',
]);

// DEXes by network for filtering/display
export const DEXES_BY_NETWORK: Record<string, string[]> = {
  "alveychain": ['elves-dex'],
  "aptos": ['aux', 'liquidswap', 'pancakeswap_aptos', 'animeswap', 'baptswap', 'liquidswap-v0-5', 'sushiswap-aptos', 'movepump-aptos', 'hyperion', 'emojicoin-fun'],
  "arbitrum": ['sushiswap_arbitrum', 'uniswap_v3_arbitrum', 'swapr_arbitrum', 'fraxswap_arbitrum', 'curve_arbitrum', 'kyberswap_elastic_arbitrum', 'kyberswap_classic_arbitrum', 'elk_finance_arbitrum', 'camelot', '3xcalibur', 'swapfish', 'arbswap_arbitrum_one', 'oreoswap', 'balancer_arbitrum', 'traderjoe-v2-arbitrum', 'magicswap', 'zyberswap', 'solidlizard', 'sharkyswap', 'alienfi', 'arbiswap', 'sterling', 'oasisswap', 'mindgames-arbitrum', 'archly-arbitrum', 'arbidex', 'apeswap-arbitrum', 'mm-finance-arbitrum', 'ramses', 'auragi', 'aegis', 'mm-finance-v3-arbitrum', 'camelot-v3', 'traderjoe-v2-1-arbitrum', 'arbswap-stableswap-arbitrum', 'whitehole-arbitrum', 'chronos', 'lfgswap-arbitrum', 'swaprum', 'solunea-arbitrum', 'arbidex-v3', 'crescentswap', 'ramses-v2', 'sushiswap-v3-arbitrum', 'dexswap', 'forge-sx', 'degenbrains', 'spartadex', 'pancakeswap-v2-arbitrum', 'pancakeswap-v3-arbitrum', 'smardex-arbitrum', 'darwinswap', 'pixelswap-arbitrum', 'antfarm-arbitrum', 'dex-on-crypto-arbitrum', 'shekelswap', 'spinaqdex', 'woken-exchange-arbitrum', 'kaleidoswap-arbitrum', 'gasx', 'uniswap-v2-arbitrum', 'dackieswap-v2-arbitrum', 'dackieswap-v3-arbitrum', 'pancakeswap-stableswap-arbitrum', 'solidly-v3-arbitrum', 'kewlswap-arbitrum', 'traderjoe-v2-2-arbitrum', 'moonbase-alpha', 'deltaswap', 'ethervista-arbitrum', 'squadswap-v2-arbitrum', 'squadswap-v3-arbitrum', 'uniswap-v4-arbitrum', 'maverick-v2-arbitrum', 'bunni-arbitrum', 'omni-exchange-v2-arbitrum', 'omni-exchange-v3-arbitrum', 'balancer-v3-arbitrum'],
  "arbitrum_nova": ['sushiswap_arbitrum_nova', 'rcpswap', 'arbswap_arbitrum_nova', 'archly-arbitrum-nova', 'arbswap-stableswap-arbitrum-nova', 'sushiswap-v3-arbitrum-nova'],
  "astr": ['polkaex_astar', 'arthswap', 'funbeast', 'astar_exchange', 'versa', 'ags_finance', 'starswap', 'zenlink_astar', 'astar-exchange-v3'],
  "aurora": ['trisolaris', 'wannaswap', 'auroraswap', 'nearpad', 'amaterasu', 'mindgames', 'polaris', 'holdr'],
  "avax": ['pangolin', 'traderjoe', 'lydia_finance', 'thorus', 'firebird_avax', 'elk_finance_avax', 'yetiswap', 'sushiswap_avalanche', 'hakuswap', 'radioshack_avalanche', 'hurricaneswap', 'apexswap', 'swapsicle', 'fraxswap_avalanche', 'spice_trade_avalanche', 'kyberswap_elastic_avalanche', 'baguette', 'soulswap_avalanche', 'kyberswap_classic_avalanche', 'traderjoe-v2-avalanche', 'onavax', 'curve_avalanche', 'vapordex', 'hunnyswap', 'flair-dex', 'glacier', 'solisnek', 'traderjoe-v2-1-avalanche', 'sushiswap-v3-avalanche', 'uniswap-v3-avalanche', 'balancer-v2-avalanche', 'dex-on-crypto-avalanche', 'canary-exchange', 'pharaoh-exchange', 'vapordex-v2', 'antfarm-avalanche', 'archly-avalanche', 'uniswap-v2-avalanche', 'pharaoh-exchange-v1', 'pyreswap-avalanche', 'traderjoe-v2-2-avalanche', 'fwx', 'uniswap-v4-avalanche', 'aquaspace', 'arena-dex', 'pangolin-v3', 'blackhole-v2', 'blackhole-v3', 'omni-exchange-v2-avalanche', 'omni-exchange-v3-avalanche', 'balancer-v3-avalanche', 'omni-exchange-v4-avalanche'],
  "base": ['leetswap-base', 'rocketswap', 'cbswap', 'ensurer', 'oasisswap-base', 'sushiswap-v3-base', 'synthswap', 'swapbased', 'horizondex-base', 'baseswap', 'velocimeter-base', 'kokonutswap-base', 'lfgswap-base', 'crescentswap-base', 'swapline-base', 'balancer-v2-base', 'sobal-base', 'dackieswap-v3-base', 'uniswap-v3-base', 'degenbrains-base', 'cloudbase', 'yum-yum-swap', 'throne-v3-base', 'alien-base', 'baso-finance', 'icecreamswap-base', 'bakeryswap-base', 'throne-v2-base', 'archly-base', 'soswap', 'derpdex-base', 'pixelswap-base', 'diamondswap', 'pancakeswap-v3-base', 'pancakeswap-v2-base', 'aerodrome-base', 'smardex-base', 'kyberswap-elastic-base', 'dackieswap-v2-base', 'plantbaseswap', 'moonbase', 'equalizer-base', 'dex-on-crypto-base', 'iziswap-base', 'area-51-alien-base', 'sushiswap-v2-base', 'sharkswap-base', 'torus', 'citadelswap', 'satori-base', 'uniswap-v2-base', 'solidly-v3-base', 'infusion', 'candyswap', 'basex', 'robots-farm-base', 'bunnyswap', 'aerodrome-slipstream', 'memebox-base', 'swapbased-v3', 'baseswap-v3', 'curve-base', 'bluedex', 'synthswap-v3', 'marswap-base', 'dejungle', 'ethervista-base', 'alien-base-v3', 'squadswap-base', 'squadswap-v3-base', 'x7-finance-base', 'fwx-base', 'kim-v4-base', 'kim-v2-base', 'henjin', 'uniswap-v4-base', 'treble-v2', 'maverick-v2-base', 'virtuals-base', '9mm-v3-base', '9mm-v2-base', 'deltaswap-base', 'treble-v4', 'rubicon-base', 'hydrex-integral', 'kewlswap-base', 'quickswap-v2-base', 'quickswap-v4-base', 'omni-exchange-v2-base', 'omni-exchange-v3-base', 'omni-exchange-v4-base', 'pancakeswap-infinity-clmm-base', 'balancer-v3-base', 'bunni-base'],
  "bch": ['benswap', 'mistswap', 'tropical_finance', '1bch', 'tangoswap', 'cowswap_smartbch', 'emberswap', 'lawswap'],
  "beam": ['beam-swap'],
  "bitgert": ['sphynx_brise', 'icecreamswap'],
  "bitkub_chain": ['diamon_finance', 'baryon-network-bitkub-chain', 'udonswap', 'ponder-finance', 'cmswap-kub'],
  "bitrock": ['rockswap', 'popswap'],
  "boba": ['oolongswap', 'swapperchan', 'sushiswap-boba', 'sushiswap-v3-boba', 'oku-trade-boba'],
  "bsc": ['pancakeswap_v2', 'jswap_bsc', 'apeswap_bsc', 'mdex_bsc', 'biswap', 'sushiswap_bsc', 'firebird_bsc', 'impossible_finance', 'babyswap', 'wault_finance', 'mars_ecosystem', 'jetswap_bsc', 'elk_finance_bsc', 'annex_finance_bsc', 'autoshark_finance', 'julswap', 'leonicornswap', 'yoshi_exchange_bsc', 'empiredex_bsc', 'polkaex_bsc', 'knightswap', 'impossible_finance_v3', 'moonlift', 'sphynx_swap', 'justmoney_bsc', 'radioshack_bsc', 'pyeswap_bsc', 'bakeryswap', 'pls2e', 'winery_swap', 'nomiswap', 'safemoon_swap', 'fstswap', 'dddx', 'swych', 'orbitalswap', 'pandora_digital_swap', 'fraxswap_bsc', 'bridges', 'whaleswap', 'pinkswap', 'baryon_network', 'dooar_bsc', 'spice_trade_bsc', 'kyberswap_elastic_bsc', 'cone_exchange', 'alium', 'dao_swap', 'ellipsis_finance', 'planet_finance', 'babydogeswap', 'nomiswap_stable', 'kyberswap_classic_bsc', 'cakewswap_bsc', 'corgiswap', 'dinosaureggs', 'niob', 'padswap-bsc', 'w3swap', 'openocean', 'thena', 'kyotoswap', 'lif3-bsc', 'pancakeswap_stableswap', 'traderjoe-bsc', 'traderjoe-v2-bsc', 'archly-bsc', 'definix', 'uniswap-bsc', 'iziswap-bsc', 'pancakeswap-v3-bsc', 'traderjoe-v2-1-bsc', 'thena-fusion', 'saitaswap-bsc', 'hkswap', 'stronghands-dex-v2', 'surge-protocol-bsc', 'intercroneswap-bsc', 'sushiswap-v3-bsc', 'magicfox', 'veplus', 'biswap-v3', 'acsi-finance', 'usdfi', 'smardex-bsc', 'ampleswap-bsc', 'dex-on-crypto', 'allinxswap-bsc', 'diamondswap-bsc', 'creamswap', 'biswap-v3-1', 'melegaswap', 'degendex-bsc', 'donaswap-v3-bsc', 'woken-exchange-bsc', 'lif3-v3-bsc', 'lovely-swap', 'orion-bsc', 'uniswap-v2-bsc', 'pancakeswap-v1-bsc'],
  "bttc": ['justmoney_bttc', 'kyberswap_classic_bttc', 'elk_finance_bittorrent', 'torrswap', 'intercroneswap-bittorent', 'sushiswap-v3-bittorrent', 'sushiswap-v2-bittorrent', 'spookyswap-bittorent', 'mdex-bittorent'],
  "canto": ['canto_dex', 'forteswap', 'cantoswap', 'velocimeter', 'velocimeter_v2', 'leetswap-canto', 'velocimeter-v3'],
  "celo": ['ubeswap', 'sushiswap_celo', 'celodex', 'uniswap_v3_celo', 'curve-celo', 'ubeswap-v3', 'velodrome-finance-slipstream-celo'],
  "cfx": ['swappi'],
  "core": ['icecreamswap-core', 'lfgswap-core', 'shadowswap', 'archerswap', 'nskswap', 'spoon-exchange', 'satoshicoreswap', 'sushiswap-v3-core', 'woofswap-core', 'dex-on-crypto-core', 'cuanswap', 'icecreamswap-v3-core', 'agus-dex-core', 'openex-core', 'glyph-exchange-v2', 'oreswap-core', 'wizardswap-core', 'corex', 'sushiswap-v2-core', 'viridian', 'pipiswap', 'glyph-exchange-v4', 'falcox-swap'],
  "cro": ['vvs', 'cronaswap', 'crodex', 'elk_finance', 'mm_finance', 'firebird_cronos', 'crowfi', 'photonswap', 'empiredex_cronos', 'duckydefi', 'cyborgswap', 'kryptodex', 'annex_finance', 'radioshack_cronos', 'cougar_exchange', 'kyberswap_elastic_cronos', 'candycity_finance', 'aliendex', 'croswap', 'phenix-finance-cronos', 'mm-finance-v3-cronos', 'vvs-v3', 'archly-cronos', 'ebisus-bay'],
  "defimetachain": ['vanillaswap-v2-defimetachain', 'vanillaswap-v3-defimetachain'],
  "dfk": ['defi_kingdoms_crystalvale'],
  "dogechain": ['dogeswap', 'dogeshrek', 'bourbon_defi', 'pupswap', 'yodeswap', 'kibbleswap', 'quickswap_dogechain', 'fraxswap_dogechain', 'radioshack-dogechain', 'toolswap', 'degendex-dogechain', 'wojak-finance-dogechain'],
  "ela": ['glide_finance', 'elk_finance_elastos'],
  "elysium": ['elysiumswap'],
  "enuls": ['pheasantswap'],
  "eos_evm": ['eoswap-finance', 'noahswap', 'neutroswap', 'frogge-finance'],
  "eth": ['uniswap_v2', 'sushiswap', 'uniswap_v3', 'shibaswap', 'templedao', 'standard_ethereum', 'swapr_ethereum', 'degenswap', 'concave', 'radioshack_ethereum', 'elk_finance_ethereum', 'integral_size', 'kyberswap_elastic', 'fraxswap_ethereum', 'defi_swap', 'curve', 'apeswap_ethereum', 'sakeswap', 'dooar_ethereum', 'spice_trade_ethereum', 'unicly', 'verse', 'pancakeswap_ethereum', 'kyberswap_classic_ethereum', 'safemoonswap_ethereum', 'balancer_ethereum', 'solidlydex', 'antfarm-ethereum', 'pancakeswap-v3-ethereum', 'smardex-ethereum', 'whiteswap', 'saitaswap-ethereum', 'surge-protocol-eth', 'sashimiswap', 'pepedex', 'x7-finance', 'traderjoe-v2-1-ethereum', 'hopeswap', 'dex-on-crypto-ethereum', 'sushiswap-v3-ethereum', 'solidly-v3', '9inch-ethereum', 'justmoney-ethereum', 'wagmi-ethereum', 'lif3-ethereum', 'bitswap', 'blueprint', 'orion-ethereum', 'vvs-v3-ethereum', 'convergence-finance-v2', 'archly-ethereum', 'marswap-ethereum', 'ethervista', 'pancakeswap-stableswap-ethereum', 'x7-finance-ethereum', 'uniswap-v4-ethereum', 'maverick-v2-eth', 'deltaswap-ethereum', 'ring-exchange-ethereum', 'ekubo-ethereum', 'bunni-ethereum', 'balancer-v3-ethereum'],
  "ethereum_classic": ['hebeswap', 'soy_finance_etc', 'etcmc', 'etcswap-v3', 'etcswap-v2'],
  "ethw": ['uniswap_v2_ethpow', 'radioshack-ethw', 'powswap', 'uniwswap', 'lfgswap', 'powerswap', 'cakewswap', 'zergswap-v2', 'zergswap-v3'],
  "evmos": ['diffusion', 'cronus_finance', 'evmoswap', 'spacefi', 'forge'],
  "exosama": ['khaos_exchange'],
  "filecoin": ['puppyswap', 'themis-pro', 'sushiswap-v3-filecoin', 'oku-trade-filecoin', 'archly-filecoin', 'sushiswap-v2-filecoin'],
  "findora": ['fairyswap'],
  "flare": ['pangolin-flare', 'blazeswap-flare', 'enosys-flare', 'xenos-swap-flare', 'sparkdex-v2', 'sparkdex-v3', 'sparkdex-v3-1', 'enosys-v3-flare'],
  "ftm": ['spookyswap', 'spiritswap', 'sushiswap_fantom', 'soulswap', 'firebird_fantom', 'dfyn_fantom', 'jetswap_fantom', 'elk_finance_ftm', 'morpheus_swap', 'paintswap', 'fbomb_finance', 'yoshi_exchange_ftm', 'wigoswap', 'tomb_swap_fantom', 'protofi', 'darkknight', 'solidly', 'excalibur', 'wingswap', 'hyperjump_ftm', 'fraxswap_fantom', 'curve_ftm', 'spiritswap_v2', 'radioshack_fantom', 'kyberswap_elastic_fantom', 'kyberswap_classic_fantom', 'equalizer', 'beethoven_x_fantom', 'redemption', 'magikswap', 'metropolis', 'skullswap', 'archly-ftm', 'wagmi-fantom', 'sushiswap-v3-fantom', 'velocimeter-fantom', 'skeleton-finance', 'solidly-v3-fantom', 'lif3-v3-fantom', 'orion-fantom', 'spookyswap-v3', 'memebox-fantom', 'degen-express', 'pyreswap-fantom'],
  "fuse": ['voltage_finance', 'elk_finance_fuse', 'sushiswap_fuse', 'sushiswap-v3-fuse', 'voltage-finance-v3', 'voltage-finance-v4'],
  "glmr": ['beamswap', 'stellaswap', 'thorus_moonbeam', 'solarflare', 'lunardex', 'fraxswap_moonbeam', 'zenlink_moonbeam', 'padswap_moonbeam', 'curve_moonbeam', 'stellaswap-v3', 'beamswap-v3', 'sushiswap-v3-moonbeam', 'oku-trade-moonbeam', 'stellaswap-v4'],
  "godwoken": ['yokaiswap'],
  "hedera_hashgraph": ['saucerswap', 'saucerswap-v2', 'heliswap'],
  "humanode": ['impossible-finance-humanode'],
  "hypra_network": ['retherswap'],
  "iotx": ['mimo', 'elk_finance_iotex', 'loxodrome-iotex'],
  "kai": ['becoswap', 'kaidex', 'kaidex_v3'],
  "kaia": ['claimswap', 'defi_kingdoms_serendale', 'klayswap', 'klayswap-v3', 'kaiaswap-klaytn', 'dragonswap-v2-kaia', 'dragonswap-v3', 'mermaidswap', 'capybaradex-v2', 'capybaradex-v3'],
  "kava": ['photonswap_kava', 'jupiter_swap', 'elk_finance_kava', 'surfswap', 'equilibre', 'archly-kava', 'curve-kava', 'wagmi-kava', 'kinetix-v3', 'sushiswap-v2-kava', 'sushiswap-v3-kava', 'iziswap-kava'],
  "kcc": ['kuswap', 'mojitoswap', 'elk_finance_kcc'],
  "lightlink_phoenix": ['elektrik'],
  "linea": ['syncswap-linea', 'horizondex', 'echodex', 'leetswap-linea', 'pancakeswap-v2-linea', 'pancakeswap-v3-linea', 'kyberswap-elastic-linea', 'iziswap-linea', 'pheasantswap-linea', 'pixelswap-linea', 'lynex-linea', 'sushiswap-v3-linea', 'metavault-v3-linea', 'metavault-v2-linea', 'velocore-v2-linea', 'chimp-exchange', 'nile', 'secta-finance-v2', 'secta-finance-v3', 'satori-linea', 'lynex-v2-linea', 'nile-v1', 'line-hub-v2', 'line-hub-v3', 'sushiswap-v2-linea', 'oku-trade-linea', 'syncswap-v2-1-linea', 'dackieswap-v2-linea', 'dackieswap-v3-linea', 'etherex'],
  "loopnetwork": ['sphynx-loop-network'],
  "manta_pacific": ['leetswap-manta', 'mantaswap', 'apertureswap', 'iziswap-manta-pacific', 'pacificswap', 'quickswap-v3-manta-pacific', 'cetoswap', 'firefly', 'gull-network', 'oku-trade-manta-pacific'],
  "mantle": ['fusionx-v2', 'fusionx-v3', 'agni-finance', 'crust-finance', 'iziswap-mantle', 'swapsicle-v2-mantle', 'velocimeter-mantle', 'butter-xyz', 'merchant-moe-mantle', 'cleopatra-exchange', 'stratum-exchange', 'archly-mantle', 'methlab', 'merchant-moe-liquidity-book-mantle', 'tropicalswap', 'crust-finance-v2', 'funny-money'],
  "metis": ['netswap', 'tethys', 'standard', 'agora_swap', 'hermes_protocol', 'hyperjump_metis', 'wagmi-metis', 'sushiswap-v3-metis', 'archly-metis', 'hercules-v2', 'hercules-v3', 'sushiswap-v2-metis'],
  "milkada": ['milkyswap-milkada', 'occamx', 'muesliswap-milkada', 'tangleswap-milkomeda-cardano'],
  "mode": ['dyorswap-mode', 'kim', 'swapmode', 'supswap', 'poolshark', 'archly-mode', 'dackieswap-v2-mode', 'dackieswap-v3-mode', 'kim-v4', 'iziswap-mode', 'velodrome-finance-v2-mode', 'balancer-v2-mode', 'velodrome-finance-slipstream-mode'],
  "movr": ['solarbeam', 'huckleberry', 'sushiswap_moonriver', 'firebird_movr', 'zenlink_moonriver', 'elk_finance_movr', 'seadex', 'zircon', 'fraxswap_moonriver', 'sushiswap-v3-moonriver'],
  "mtr": ['voltswap_meter', 'symmetric-finance-meter'],
  "multivac": ['vax'],
  "mxc_zkevm": ['mxc-swap'],
  "neon_evm": ['moraswap-v2', 'sobal', 'elk-finance-neon', 'icecreamswap-neon', 'archly-neon', 'moraswap-v3', 'vibrant-finance'],
  "nrg": ['energiswap'],
  "oasis": ['yuzuswap_oasis_emerald', 'duneswap', 'valleyswap', 'gemkeeper', 'lizard-exchange'],
  "oasys": ['tealswap', 'tealswap-v3', 'gaming-dex-oasys'],
  "one": ['viperswap', 'defi_kingdoms', 'sushiswap_harmony', 'wagmidao', 'fuzz_finance', 'elk_finance_one', 'openswap', 'bossswap', 'tranquil_finance', 'lootswap', 'foxswap', 'hermesdefi', 'swap-country'],
  "onus": ['miaswap'],
  "opbnb": ['binaryswap', 'luigiswap', 'fourdex', 'knightdex', 'pixelswap-opbnb', 'mobydEX', 'rocketswap-opbnb', 'opbnbswap', 'cubiswap', 'allinxswap-opbnb', 'pancakeswap-v2-opbnb', 'pancakeswap-v3-opbnb', 'derpdex-opbnb', 'dex-on-crypto-opbnb', 'thena-opbnb', 'udex'],
  "optimism": ['uniswap_v3_optimism', 'zipswap', 'velodrome', 'curve_optimism', 'radioshack_optimism', 'kyberswap_elastic_optimism', 'kyberswap_classic_optimism', 'fraxswap_optimism', 'elk_finance_optimism', 'beethoven_x_optimism', 'openxswap', 'archly-optimism', 'sushiswap-v3-optimism', 'velodrome-finance-v2', 'swapline-optimism', 'uniswap-v2-optimism', 'dackieswap-v2-optimism', 'dackieswap-v3-optimism', 'velodrome-finance-slipstream', 'solidly-v3-optimism', 'sushiswap-v2-optimism', 'squadswap-v2-optimism', 'squadswap-v3-optimism', 'superswap', 'uniswap-v4-optimism', 'rubicon-optimism', 'omni-exchange-v2-optimism', 'omni-exchange-v3-optimism', 'balancer-v3-optimism'],
  "platon_network": ['dipoleswap'],
  "polygon_pos": ['quickswap', 'sushiswap_polygon_pos', 'apeswap_polygon', 'dinoswap', 'firebird_finance_polygon', 'comethswap', 'dfyn', 'elk_finance_polygon', 'wault_finance_polygon', 'jetswap_polygon', 'polydex', 'gravity_finance', 'polycat_finance', 'algebra_finance', 'tetuswap', 'uniswap_v3_polygon_pos', 'nachoswap', 'greenhouse_dex', 'justmoney_polygon_pos', 'radioshack_polygon_pos', 'dystopia', 'vulcandex', 'kyberswap_classic_polygon', 'auraswap', 'fraxswap_polygon_pos', 'curve_polygon_pos', 'honeyswap_polygon', 'meshswap', 'mm-finance-polygon', 'spice_trade_polygon', 'kyberswap_elastic_polygon', 'quickswap_v3', 'balancer_polygon', 'lif3-polygon', 'crowdswap-polygon', 'satin-exchange', 'phenix-finance-polygon', 'safemoonswap-polygon', 'purplebridge', 'sushiswap-v3-polygon', 'pearl-exchange', 'retro', 'pearlfi-v1-5', 'smardex-polygon', 'archly-polygon', 'dex-on-crypto-polygon', 'mama-defi', 'ix-swap', 'lif3-v3-polygon', 'dooar-polygon', 'orion-polygon', 'uniswap-v2-polygon', 'squadswap-v2-polygon', 'squadswap-v3-polygon', 'uniswap-v4-polygon', 'gt3', 'w-dex-polygon'],
  "polygon_zkevm": ['quickswap-polygon-zkevm', 'doveswap-v3', 'leetswap-zkevm', 'sushiswap-v3-polygon-zkevm', 'pancakeswap-v2-polygon-zkevm', 'pancakeswap-v3-polygon-zkevm', 'balancer-v2-polygon-zkevm', 'antfarm-polygon-zkevm', 'leetswap-polygon-zkevm', 'sushiswap-v2-polygon-zkevm', 'oku-trade-polygon-zkevm'],
  "pulsechain": ['pulsex', 'pulsex-v2', 'velocimeter-pulsechain', 'eazyswap', 'pulse-rate', 'phux', '9inch', 'sparkswap', '9mm-v3', '9mm-v2', 'dextop', 'pulsegun', 'wizardswap-pulsechain', 'function-island', 'pdex-vision'],
  "rollux": ['pegasys-v3-rollux'],
  "ronin": ['katana', 'katana-v3'],
  "scroll": ['scrollswap', 'punkswap', 'leetswap-scroll', 'spacefi-scroll', 'iziswap-scroll', 'sanctuary', 'quillswap', 'icecreamswap-scroll', 'skydrome', 'kyberswap-elastic-scroll', 'syncswap-scroll', 'papyrus-swap', 'cattieswap', 'luigiswap-scroll', 'metavault-v2-scroll', 'metavault-v3-scroll', 'coffee-dex', 'zadafinance', 'zebra-scroll', 'zebra-v2-scroll', 'sushiswap-v3-scroll', 'z-protocol', 'oku-trade-scroll', 'skydrome-v2', 'tokan-exchange', 'nuri-v2', 'sushiswap-v2-scroll', 'syncswap-v2-1-scroll', 'scribe', 'nuri-legacy', 'maverick-v2-scroll'],
  "sdn": ['polkaex_shiden', 'standard_protocol'],
  "sei_network": ['astroport-sei'],
  "sepolia_testnet": ['uniswap-v3-sepolia-testnet', 'uniswap-v2-sepolia-testnet'],
  "shibarium": ['woof-finance', 'shibbex', 'shipedex', 'dogswap', 'ball-exchange-shibarium', 'piswap', 'leetswap-shibarium', 'shiniswap', 'woofswap', 'marswap', 'chewyswap', 'dex-on-crypto-shibarium', 'punkswap-shibarium', 'shibaswap-shibarium', 'shibarium-fun'],
  "shimmerevm": ['icecreamswap-shimmerevm', 'shimmersea', 'tangleswap-shimmerevm', 'iotabee-shimmerevm', 'swapline-shimmerevm', 'cyberglow'],
  "solana": ['raydium', 'orca', 'raydium-clmm', 'fluxbeam', 'meteora', 'dexlab', 'daos-fun', 'pumpswap', 'virtuals-solana', 'boop-fun', 'saros-amm', 'meteora-dbc', 'byreal', 'pancakeswap-v3-solana', 'meteora-damm-v2', 'raydium-launchlab', 'pump-fun', 'saros-dlmm'],
  "songbird": ['pangolin-songbird', 'oracleswap', 'blazeswap', 'enosys-dex', 'featherswap', 'xenos-swap-songbird', 'enosys-dex-v3'],
  "starknet_alpha": ['jediswap-starknet-alpha', '10kswap-starknet-alpha', 'ekubo', 'nostra', 'starkdefi'],
  "step_network": ['step-exchange'],
  "sui_network": ['bluemove', 'cetus', 'flameswap', 'suiswap', 'kriya-dex', 'turbos-finance', 'bluefin', 'flow-x', 'magma-finance', 'flowx-clmm', 'momentum', 'fullsail-finance'],
  "sxn": ['sharkswap'],
  "tenet": ['tenx', 'tendieswap'],
  "thundercore": ['laserswap', 'sushiswap-v3-thundercore', 'sushiswap-v2-thundercore'],
  "tlos": ['omnidex', 'elk_finance_telos', 'zappy', 'sushiswap_telos', 'apeswap_telos', 'archly-telos', 'swapsicle-telos', 'icecreamswap-telos', 'swapsicle-v2-telos', 'velocore-v2-telos', 'symmetric-finance', 'hexaswap', 'polaris-telos', 'vapordex-v2-telos', 'meridian-swap', 'oku-trade-telos'],
  "tombchain": ['lif3'],
  "tomochain": ['baryon-network-viction', 'rabbitswap'],
  "ton": ['stonfi', 'dedust', 'stonfi-v2'],
  "ultron": ['ultronswap'],
  "velas": ['wagyuswap', 'astroswap', 'wavelength'],
  "wan": ['wanswap', 'rexdex', 'xflows'],
  "wemix": ['wemix_fi'],
  "xdai": ['honeyswap', 'sushiswap_xdai', 'elk_finance_xdai', 'swapr_xdai', 'bao_finance', 'levinswap_xdai', 'balancer-gnosis', 'sushiswap-v3-gnosis', 'curve-gnosis', 'oku-trade-gnosis', 'balancer-v3-gnosis'],
  "xdc": ['xswap', 'icecreamswap-xdc', 'globiance', 'xswap-v3', 'fathom-dex', 'nexus', 'oku-trade-xdc', 'curve-xdc'],
  "zkfair": ['iziswap-zkfair', 'sideswap', 'furyswap-zkfair', 'zkfairswap-zkfair'],
  "zksync": ['mute', 'spacefi_zksync', 'gemswap', 'syncswap', 'velocore', 'wagmi-zksync', 'merlin-dex', 'onsen-swap', 'solunea', 'vesync', 'starmaker', 'ezkalibur', 'zkswap-finance', 'derpdex', 'pancakeswap-v3-zksync', 'pancakeswap-v2-zksync', 'dracula-finance', 'iziswap-zksync', 'iziswap-v2-zksync', 'pixelswap-zksync', 'uniswap-v3-zksync', 'velocore-v2-zksync', 'syncswap-v2-zksync', 'archly-zksync', 'syncswap-v2-1-zksync', 'koi-finance-v3', 'zkswap-v3', 'zkswap-finance-stableswap', 'holdstation', 'syncswap-v3-zksync', 'maverick-v2-zksync'],
};

export function isGtSupported(dex?: string, version?: string): boolean {
  if (!dex) return false;
  const key = `${dex.toLowerCase()}${version ? '_' + version.toLowerCase() : ''}`;
  return ALLOW.has(key);
}

export function isPriorityDex(dex: string): boolean {
  return PRIORITY_DEXES.has(dex);
}

export function getDexesForNetwork(network: string): string[] {
  return DEXES_BY_NETWORK[network] || [];
}

export function getNetworksForDex(dexId: string): string[] {
  return Object.entries(DEXES_BY_NETWORK)
    .filter(([_, dexes]) => dexes.includes(dexId))
    .map(([network]) => network);
}
